server:
  port: 9100
#  servlet:
#    context-path: /a

logging:
  level:
    io.dapr: DEBUG

# Spring
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: a
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    name: account-service
    jdbc-url: jdbc:postgresql://localhost:5432/kadmos
    username: postgres
    password: atefeh
    driver-class-name: org.postgresql.Driver
    tlsEnabled: true
    minimum-idle: 10
    maximum-pool-size: 100
    idle-timeout: 5000
    max-lifetime: 60000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    pageable:
      page-size: 100

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true

  eureka:
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
    client:
      serviceUrl:
        defaultZone: ${EUREKA_SERVER:http://127.0.0.1:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
    trace:
      http:
        include: RESPONSE_HEADERS
  endpoint:
    health:
      show-details: 'ALWAYS'
    loggers:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
