version: '3.3'
services:
  saveAccount-service:
    image: saveAccount-service
    build:
      context: rest-controller
      dockerfile: Dockerfile
    container_name: saveAccount-b-service
    ports:
      - 8081:9100
    enviroment:
      EUREKA_SERVER: http://api-registry-service:8761/eureka
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: atefeh