version: '3.3'
services:
  a-saving-account-service:
    image: saving-account-service
    build:
      context: ..
      dockerfile: saveAccount/rest-controller/Dockerfile
    container_name: a-saving-account-service
    ports:
      - 8080:9100
    volumes:
      - ${PWD}/saving-a-logs:/app/logs
    environment:
      EUREKA_SERVER: http://api-registry-service:8761/eureka
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz@WSX

